name: "Valjean JSON Schema Validator"
description: "Validate JSON using remote schemas"

branding:
  label: "Valjean JSON Schema Validator"
  icon: "book"
  color: "red"

inputs:
  schema-url:
    description: "the url to the JSON schema"
    required: true
  target-dir:
    description: "the directory (or directories, comma separated) containing the json files to validate"
    required: true
  all-errors:
    description: "enable allErrors on AJV validator"
    required: false
    default: "false"
  ajv-strict:
    description: "enable AJV's strict mode, which does not adhere to the JSON Schema spec"
    required: false
    default: "false"
  draft-version:
    description: The draft version to use; supports 2019 or 2020
    required: false
    default: "2020"

runs:
  using: "node20"
  main: "dist/index.js"
